definitions view
Benni0706/DefNotator pull request #71
Opened 2024-02-04 17:18 UTC by Benni0706

2024-02-06 17:10 UTC, roriwa requested changes

2024-02-06 17:10 UTC, roriwa commented on src/frontend/src/router/index.ts
> +      path: '/:datasetName/definitions',
`/dataset/:datasetName/definitions`

2024-02-06 17:10 UTC, roriwa commented on src/frontend/src/router/index.ts
> +      path: '/:datasetName/definitions',
bei `Criteria` auch

2024-02-06 17:10 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +  await getDatasetDefinitions();
```ts
await Promise.all([
  getDatasetDefinitions(),
  getAllDefinitions(),
])
```

2024-02-06 17:10 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +const props = defineProps(['user']);
```ts
const props = defineProps<{
  user: UserType,  // dunno from where
}>();
```

2024-02-07 18:59 UTC, Benni0706 commented on src/frontend/src/views/Definitions.vue
> +  await getDatasetDefinitions();
Das wird ausgeführt, wenn eine beliebige asynchrone Funktion fertig ist?

2024-02-09 16:24 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +  await getDatasetDefinitions();
das führt beide funktionen gleichzeitig aus (also schneller als beide nacheinander)

2024-02-10 12:32 UTC, roriwa requested changes

2024-02-10 12:32 UTC, roriwa commented on src/frontend/src/views/Criteria.vue
> +import listElement from '../components/ListElement.vue';
import **L**istElement

2024-02-10 12:32 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +const tab = ref<Number>(0);
ref<**n**umber>()

2024-02-10 12:32 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +      getAllDefinitions()
await Promise.all([...]) für beide

2024-02-10 12:32 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +    getAllDefinitions()
await Promise.all([...]) für beide

2024-02-10 12:32 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +    getAllDefinitions()
await Promise.all([...]) für beide

2024-02-10 12:32 UTC, roriwa commented on src/frontend/src/views/Criteria.vue
> +        <listElement @remove="unassignCriterion(criterion.id)" v-for="criterion in datasetCriteria" :data="criterion" />
<**L**istElement ...

2024-02-17 13:32 UTC, roriwa approved these changes
lgtm

2024-02-17 13:32 UTC, roriwa commented on src/frontend/src/views/Definitions.vue
> +    console.log(response.data)
debug statement hinterlassen

2024-02-17 15:24 UTC, merged